### ISSUE TITLE
Whitelist functionality

### ISSUE THREAD

**Issue by nathanmiddleton** [M-Reimer/togglereferrer#1]
Some kind of whitelist feature would be great! Especially for local services where a referrer could be used and useful and you know it's safe.

**Comment by M-Reimer** [comment]
In my opinion the "Referrer" is never "useful". I would have dropped this from the HTTP standard long ago.
But that's just my opinion.
My Addon uses the following API:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites
Scroll down to "referrersEnabled"
This setting can only be either "true" or "false". There is no way to get any whitelist feature in there. Doing so would require a complete rewrite of the Addon as this would require to manually override the Javascript API and the HTTP header.

But some of the Referrer manipulation Addons, available on addons.mozilla.org, could actually work well together with my Addon as long as they set the "Referer" header in their code. If you find something that works for you, please post a link here.

**Comment by stonecrusher** [comment]
I think [SmartReferrer](https://addons.mozilla.org/firefox/addon/smart-referer/) can do what @nathanmiddleton wants.

**Comment by M-Reimer** [comment]
Maybe. Ideally use it in combination with "Toggle Referrer", as "SmartReferrer" doesn't prevent JavaScript to still read the unmodified/unspoofed referrer. It just modifies the HTTP header but doesn't implement an override/hook for "navigator.referrer".
