### ISSUE TITLE
Please add Pocket getpocket.com to your whitelist

### ISSUE THREAD

**Issue by richardlissimore** [M-Reimer/togglereferrer#10]
Firstly thanks for creating togglereferrer.

I'm unable to login to Mozilla's Pocket service when it's enabled so is there any chance of adding it's domain getpocket.com to the internal whitelist please? 

Thanks in advance!

**Comment by M-Reimer** [comment]
Done. New version is on its way.

**Comment by richardlissimore** [comment]
Thanks, much appreciated!
