### ISSUE TITLE
Not clear if the add-on is actually working or not

### ISSUE THREAD

**Issue by TimP69** [M-Reimer/togglereferrer#11]
In the 'details' section of the add-on, the following text appears:

> A red flag on the toolbar button makes it easy to see if you enabled the Referrer, so you don't forget to disable it again

This can easily be interpreted as meaning the add-on is enabled when the red flag is visible.  It doesn't _clearly_ explain what the red flag means.

Further, the tooltip that is shown when the flag is visible is "Referrer (enabled)", and when the flag is not visible the tooltip reads "Referrer (off)".

This is also confusing, because "enabled" and "off" are not opposites.

Can I make a suggestion regarding terminology?

Only use the terms "**enabled**" and "**disabled**" when specifically talking about the **status of the add-on**.  Do not use those terms to talk about the Referrer header itself.

Use terms like "**sent**" and "**not sent**" when talking about the **status of the header**.

Thus the text in the details section could be reworded to:

"A red flag on the toolbar button indicates that the add-on is disabled and Referrer headers are being sent.  Click the button to enable the add-on and prevent Referrer headers from being sent."

Tooltips could read:

"Referrer being sent" (when red flag is visible)
"Referrer not being sent" (when red flag is not visible)

Consistent use of {enabled|disabled} when talking about the add-on, and {sent|not sent} when talking about the header, will help reduce confusion.

**Comment by M-Reimer** [comment]
This is a common misunderstanding! The Add-on is never disabled! Actually it is not even possible to disable Add-ons anywhere else than about:addons

**Comment by TimP69** [comment]
Thank you for clarifying that.  If the add-on cannot be "disabled", then that would make the case even stronger for _not_ using the term "enabled" then, wouldn't it?  Terms should either be used in logical pairs, or not used at all.

Updated suggestion for the 'details' section:

"A red flag on the toolbar button warns you that Referrer headers **are** being sent. Click the button to prevent Referrer headers from being sent."

**Comment by M-Reimer** [comment]
> Thank you for clarifying that. If the add-on cannot be "disabled"

Actually it is even more tricky if you use the optional spoofing feature. If you use it, then "disabling" the Referrer disables the browser feature itself but enables a built-in spoofing feature which creates "Fake-Referrers" for some known problematic sites.

I don't want to talk about a "header" as this is too technical. I want to describe the Referrer as a feature and don't want to go too deep into details. And if the tooltip says "Referrer (enabled)" then it targets the feature "Referrer". This is especially tricky on Android where everything, you see, is the tooltip. That's also the reason why I have the current status in brackets.

Maybe it wouldn't be the worst idea to replace "enabled" with "on" as that's what I'm using for all my other "toggling Add-ons". But the logic of the "Red flag" will stay this way as, at least for me, the default state on my browsers is "Referrer off" and I want to see clearly if I changed that temporarily.

Any good wording for the "red flag" description which does not contain the word "header"?

**Comment by TimP69** [comment]
> Actually it is even more tricky if you use the optional spoofing feature. If you use it, then "disabling" the Referrer disables the browser feature itself but enables a built-in spoofing feature which creates "Fake-Referrers" for some known problematic sites.

So there are actually three states that need to be described, not just two.  That means {on|off} won't work either.

> Any good wording for the "red flag" description which does not contain the word "header"?

How about this set of three tooltips:

Referrer (shown) — red flag visible
Referrer (hidden) — red flag not visible and spoofing not enabled
Referrer (spoofed) — red flag not visible, but spoofing enabled

or

Referrer (allowed)
Referrer (blocked)
Referrer (spoofed)

or 

Referrer (real)
Referrer (none)
Referrer (fake)

**Comment by M-Reimer** [comment]
As "spoofing" is optional, has a warning and information text in the Add-on settings and only covers a small amount of pages at all, I don't think it helps to add a third state.

I think I'll go with "on" and "off". Just as my other toggling Add-ons use this, too.
