### ISSUE TITLE
Feature Suggestion: Option to block 'Origin' as well

### ISSUE THREAD

**Issue by mschomm** [M-Reimer/togglereferrer#12]
Trying ToggleReferrer with a website embedding Google Fonts I noticed that while the Referer Header is dropped when ToggleReferrer is active, tracking user surfing behaviour is still possible for Google (in this case) because the Origin Header remains untouched. Would it be possible to optionally drop the Origin Header as well?
![20210303-01-no-referer-but-origin](https://user-images.githubusercontent.com/28079144/109794875-9b350500-7c16-11eb-9e2a-3821c9812ce0.jpg)

**Comment by M-Reimer** [comment]
No for two reasons:
- it is out of scope for this Add-on. With the current privileges, that I request from Firefox, it wouldn't even be possible
- The risk of breaking things if this header is blocked is pretty high. I think the "Origin" header is the way less critical compared to Referer and for many sites it is required to be sent for cross origin requests for the cross origin server to determine if the request is permitted.

As I think the "Origin" header is way less critical, I even use it to unlock some problematic websites by duplicating "Origin" to "Referer" if you have the "spoofing feature" enabled:
https://github.com/M-Reimer/togglereferrer/blob/master/spoofing.js#L197

**Comment by M-Reimer** [comment]
Oh and about "google fonts": This is a big problem on its own. I decided to block them in uBlock on all my devices, but this makes some websites look ugly. To fix this, I've planned to create an Add-on which basically installs Google Fonts locally and redirects all requests back into the browser. I just didn't have time to do this, so far.

**Comment by mschomm** [comment]
Thanks for the explanation. Your planned Google Fonts extension sounds like a good thing too. 
I originally stumbled over these GDPR related problem areas coming from the other end, trying to get rid of Google Fonts and CDN browser requests for a website I've recently set up. I managed to actually get rid of them by implementing specialized caching proxies with nginx but that's only for one small website. Fixing this from the browser side is definitely more powerful.

**Comment by M-Reimer** [comment]
Ideally everyone should host all parts of his website on his own server. It is always a bad idea to use CDN hosts. I am webmaster of a small website and every single piece, I use there, is hosted directly on my server. I even went through the hassle of creating my own map tile server for a dynamic map I have on this website.

About the Google Fonts thing: I'll have a look at this as soon as I find the time for this. Still several things to find out before this can happen.
