### ISSUE TITLE
website problem

### ISSUE THREAD

**Issue by M1Aston** [M-Reimer/togglereferrer#13]
https://drimble.nl/

While referrer disabled: search function doe not work. No suggestions are shown, which makes it impossible to continue.

Referrer enabled\extension disabled: everything back to normal.

**Comment by M-Reimer** [comment]
New version with fix is on its way. But there is some chance that this breaks again in future. We'll see.

Not only their referrer checking is silly. This is also the worst search feature I've ever seen. I'm not a big fan of "search as you type" at all.

**Comment by M1Aston** [comment]
This website has never been very smooth as slick as far as its looks go. Apparently it's the same for the way it works. :-)
Thanks for checking\fixing it anyway.
