### ISSUE TITLE
[QUESTION] Aren't Firefox Referer dedicated prefs sufficient?

### ISSUE THREAD

**Issue by Cade66** [M-Reimer/togglereferrer#15]
Hi,

_Toggle Referrer_ (all versions) / _Firefox_ 93.0

I've set `network.http.referer.XOriginPolicy` = 1
NOTE : When to send a referer: 0=always (default), 1=only if base domains match, 2=only if hosts match

Next, search with a Web search engine for : `Test site for RefControl`
The link should be `http://www.stardrifter.org/cgi-bin/ref.cgi` OR `http://stardrifter.org/cgi-bin/ref.cgi`

Open the link : the page displays : **Referer: [BLANK]**
What more does the 'Toggle Referrer' extension provide? 

Thanks

**Comment by M-Reimer** [comment]
I guess it's time to close this one.

The main goal of my Add-on is to provide the button so everyone can completely disable the Referer header if he wants to.

The spoofing feature is optional and disabled by default. It is meant to make some popular websites work even if the Referer is completely off. This reduces the need to re-enable the Referer while surfing.
