### ISSUE TITLE
Toggle Referrer leads to infinite loop at Cloudfare captcha site

### ISSUE THREAD

**Issue by d4k0** [M-Reimer/togglereferrer#18]
Hi,

since a few weeks Toggle Referrer causes an infinite loop on pages using Cloudfare captcha:

![2022-07-17_21-00-15](https://user-images.githubusercontent.com/10982825/179421123-668c5722-5200-4ada-9c7e-aa2ce071b5ed.png)

![2022-07-17_21-00-53](https://user-images.githubusercontent.com/10982825/179421127-e7a5a283-91d2-4887-9886-91360abdbd64.png)

I have to turn off Toggle Referrer to get to the actual page.

Here is an example:

https://webbrowsertools.com/ip-address/

Could you please fix this?

**Comment by M-Reimer** [comment]
Can you still verify this issue?

I'm sure I had it just about a week ago on a different site and today I can access your example link without referrer. Seems like they maybe dropped the referrer check.

**Comment by d4k0** [comment]
Well, I still get an infinite loop (the site seems to have changed in the meantime):

![firefox_2022-08-27_03-45-36](https://user-images.githubusercontent.com/10982825/187009445-e0b92d08-d333-40c2-adec-c15b5c609162.gif)

When I turn off Toggle Referrer, I am immediately redirected to the page. On one attempt, after a few tries, a button was displayed to legitimize me as a human.

**Comment by M-Reimer** [comment]
This fixes it for me: https://github.com/M-Reimer/togglereferrer/commit/e1dfdd2c01f94eb73196ddc65ab8a26441b5eb21
But no guarantee that it stays this way.
