### ISSUE TITLE
Status treffend benennen

### ISSUE THREAD

**Issue by stonecrusher** [M-Reimer/togglereferrer#3]
Hi,
es ist einigermaßen verwirrend, dass hinter Toggle Referrer "aus" steht, wenn es aktiv ist und "aktiviert!" wenn es aus ist.
Der Status bezieht sich auf das Senden des Referrers, nicht auf die Extension selbst bzw. deren Aktion und das sollte der Text finde ich hergeben.

Vorschläge wären
- Toggle Referrer (Sending is on) / Toggle Referrer (Sending is off)

Oder reicht nicht sogar das Icon zur Wiedererkennung? Dann kann das in beide Richtungen weisende "Toggle" weg:
- Referrer gets sent / Referrer is blocked

**Comment by M-Reimer** [comment]
Wichtig in dem Zusammenhang ist, dass es unter Android gar kein Icon gibt und das der Text, der am Desktop "nur" Tooltip ist auf Android der Text ist mit dem mein Addon im Menü auftaucht.

Ich habe auch keinen Bock eine Spezialbehandlung für Android zu basteln. Zumal es auch für Benutzer vorteilhaft ist, wenn das gleiche Addon sich auf zwei Plattformen wenigstens ansatzweise gleich verhält.

Was hältst du von:

Referrer (aktiviert!)
Referrer (aus)

Also einfach das "Toggle" weg?

Ich habe für den Fall "Eingschaltet" bewusst einen auffälligeren Text gewählt. Meine anderen "Toggle-Addons" haben da einfach "an" stehen. Beim Referrer ist mir aber wichtig das es auffällt wenn der an ist.

**Comment by M-Reimer** [comment]
3.1.0 kommt jetzt ohne das "Toggle". Bitte um Feedback.

**Comment by stonecrusher** [comment]
Die Problematik unter Android war mir nicht bewusst und eine Extrawurst will ich auch nicht.

> Also einfach das "Toggle" weg?

Ja, finde deine Lösung auch gut, vielen Dank!

**Comment by chrnoe** [comment]
Ich finde es immer noch ziemlich verwirrend. Bei jedem "Referrer" überlege ich, ob das Plugin gemeint ist oder das HTML-Feature. Und wenn in Klammern 'aus' oder 'aktiviert' steht, weiß ich auch noch nicht wirklich sicher, worauf sich das bezieht. Ideal wäre gewesen, das Plugin nicht so wie das Feature zu nennen (erst recht, wenn das eine aus ist, wenn das andere an ist) :-). Ich habe nach konkreten Infos dazu gesucht (die Plugin-Beschreibung empfand ich da nicht als sonderlich hilfreich, sorry) und wollte hier jetzt einen Issue aufmachen und habe erst hier gesehen, dass ich wohl doch nicht der erste mit dem Problem bin.
Aber vielen Dank für's Plugin!

**Comment by stonecrusher** [comment]
Der Text bezieht sich auf das Feature "Referrer", nicht auf das Addon "Toggle Referrer".

Ist das rote Ausrufezeichen da, wird der Referrer mitgesendet und das Addon ist aus. Text: `Referrer (aktiviert!)`
Ist kein rotes Ausrufezeichen da, wird der Referrer nicht gesendet und das Addon ist an. Text: `Referrer (aus)`

Ist nicht gleich ersichtlich, aber wenn man sich es mal gemerkt hat, fällt es nicht mehr auf.

**Comment by M-Reimer** [comment]
Einfach ignorieren das es ein Add-on dafür gibt. Das Add-on legt einen Menüeintrag an und dabei habe ich zumindest probiert möglichst nahe an dem zu sein was "Firefox-standard" wäre (deshalb auch die Farbgebung des Icons).

Und wenn Firefox selber einen Menüeintrag für den Referrer hätte, dann würde der sich ganz sicher auf das Feature beziehen.

**Comment by chrnoe** [comment]
@stonecrusher, das war deutlich, diese Info in der Klarheit habe ich gesucht! Danke! Und klar, wenn man es einmal hat ...
