### ISSUE TITLE
How to set the spoofed referer? (Referrer Spoofing)

### ISSUE THREAD

**Issue by Herzogdb** [M-Reimer/togglereferrer#4]
Hi,
I see the option to turn on the optional referring spoofing feature in the preferences but it does not have a place to enter a URL. For example if I want to show www.example.com as the referrer where do I enter this?

**Comment by M-Reimer** [comment]
You can't enter this. It is meant to **automatically** spoof for problematic servers. Nothing you have to fiddle with. If you have such sites that don't work without referrer, then just open an issue with the website URL.

**Comment by Herzogdb** [comment]
Ok understood. Any suggestions on how I can specify the URL, perhaps with a different tool? That's what I would call spoofing (being able to define the URL myself).

**Comment by M-Reimer** [comment]
"Toggle Referrer" is meant to do what it says: Toggle the referrer between on and off.
And to be able to have this on "off" for as long as possible (and so to effectively get rid of this "feature" at all) the optional spoofing feature was added to trick problematic servers into thinking they get a valid referrer while they actually just get delivered what they want to see by my spoofing routine.

Why do you want to spoof a "wrong" referrer? This actually is a way worse idea than just to disable it completely as you may run into way more problems you already get with a completely disabled referrer.

If, for whatever reason, you want to modify this header, you could do it with something like this:
https://addons.mozilla.org/de/firefox/addon/simple-modify-header/

**Comment by CrafterLaughter** [comment]
Brilliant add-on.  I see you have all the mobile aliexpress urls in the spoof list.  However, on desktop with regular aliexpress.com I cannot get Aliexpress to rend the shipping choices on product pages or the username and password fields on the sign on page for Aliexpress unless I disable the togglereferrer addon.  Can you please add aliexpress.com to the spoof list?  Thank for all your efforts.

**Comment by M-Reimer** [comment]
I don't use AliExpress at all.

Please create a new issue for this as I need someone to test this (I don't have and don't want an account).
