### ISSUE TITLE
Is it possible to add the current referrer address as mouseover?

### ISSUE THREAD

**Issue by ralrra** [M-Reimer/togglereferrer#5]
Hello,

is it possible to add an option, that the referrer adress is shown somewhere e.g. in the mouseover. In theory is the address obvious but for me it would be interesting to know.
Thanks and thanks for your good work!
BR
ralrra

**Comment by M-Reimer** [comment]
I don't know what you actually mean with that. Please explain more in detail.

**Comment by ralrra** [comment]
Hallo Herr Reimer,

Ich machs mal auf Deutsch. Einfach das man z.B. im Mouseover quasi die Seite angezeigt sieht (also den aktuellen Referrer der mitgesendet wird) von der man kommt.

Viele Grüße
Thomas

Am 1. März 2020 11:26:51 MEZ schrieb Manuel Reimer <notifications@github.com>:

**Comment by M-Reimer** [comment]
Das ist nicht so einfach.

- Wenn der Referrer ausgeschaltet ist (keine rote Markierung am Button), dann gibt es keinen Referrer mehr. Auch mein Addon kennt ihn nicht weil Firefox ihn nicht mehr sendet.
- Wenn der Referrer eingeschaltet ist, dann gibt es viele davon. Es gibt den, der beim "Betreten" der Seite gesendet wurde, dann gibt es für jedes Element wieder die Adresse der eigentlichen Seite als Referrer, ...
- Der Referrer wird (wenn er denn gesendet wird) nirgends gespeichert. Er geht an den Server und gut. Ich könnte mich da reinschalten um ihn mitzulesen, aber das erfordert weitere Berechtigungen und ist auch kein unerheblicher Aufwand.

Da es in der geplanten "Standardeinstellung" (Referrer aus) ohnehin nichts zum Anzeigen gibt, werde ich mir den Aufwand nicht machen. Lieber verfeinere ich weiter meine "Spoofing-Liste" damit noch mehr Seiten ganz ohne Referrer gehen.
