### ISSUE TITLE
Cannot login on ebay-kleinanzeigen.de

### ISSUE THREAD

**Issue by stonecrusher** [M-Reimer/togglereferrer#6]
Hi,
erst mal danke für das Pflegen des Addons!
Ich weiß nicht, ob es von einem Update kommt, aber bei ausgeschaltetem Referrer (mit Spoofing) kann ich mich nicht auf https://www.ebay-kleinanzeigen.de/ einloggen.
Ich lande in einer Schleife auf https://www.ebay-kleinanzeigen.de/m-einloggen.html?targetUrl=/
Deaktiviere ich das togglereferrer-addon, dann geht's.
Beste Grüße

**Comment by M-Reimer** [comment]
Danke für die Meldung.

Nach kurzem Testen sieht das aber eher nach einen Update auf der Seite von ebay-kleinanzeigen aus. Wieder mal ein gutes Beispiel wie man den Referrer definitiv **nicht** verwenden sollte. Sobald **kein** Referrer gesendet wird (Spoofing kann auch ganz aus sein) spielt die Seite komplett verrückt.

Neue Version (4.1.0) ist auf dem Weg.

Add-on deaktivieren ist übrigens unnötig! Dafür gibt es ja den Toolbar-Button. Immer wenn das "rote Ausrufezeichen" dran ist wird der Referrer komplett unfiltriert gesendet. Eben dafür ist er da, denn Seiten die ohne "Original-Referrer" nicht gehen wird es immer geben.

**Comment by stonecrusher** [comment]
Danke für die schnelle Reaktion und den Fix!

Um es temporär abzuschalten, nutze ich den Toolbarbutton.

Zum debuggen - um wirklich sicherzustellen, dass es am Addon liegt - deaktiviere ich das ganze Ding.
Hat mich in der Vergangenheit schon viel Zeit gekostet, da einige Addons trotz "ausgeschaltet"-Status doch noch irgendwie interferieren (z.B. Injektion eines leeres CSS-Stylesheets, CSP Probleme usw)
