### ISSUE TITLE
spoofing: de.aliexpress.com

### ISSUE THREAD

**Issue by stonecrusher** [M-Reimer/togglereferrer#7]
Hi!
Leider müsste auch bei https://de.aliexpress.com/ nachgebessert werden.
Referrer aus:
![2020-06-05 18_48_59-DE AliExpress](https://user-images.githubusercontent.com/1388389/83903257-15a32800-a75e-11ea-84fe-e5d9727136be.png)
Mit Referrer an funktioniert's:
![2020-06-05 18_49_34-DE AliExpress](https://user-images.githubusercontent.com/1388389/83903272-1b007280-a75e-11ea-8871-31ecf767f0c2.png)
Grüße ins Wochenende!

**Comment by M-Reimer** [comment]
**Könnte** mit der aktuellen Version gehen. Es muss erlaubt werden das zwischen aliexpress-Domains beliebige aliexpress-Domains als Referrer gesendet werden. Dann wird mir das Login-Feld komplett angezeigt. Bei der Gelegenheit habe ich die Regelstruktur mal komplett überarbeitet, denn es wurden langsam echt zu viele aliexpress-Domains die berücksichtigt werden müssen.

Ob man sich wirklich einloggen kann habe ich nicht getestet. Wenn das nicht geht, dann eben Referrer für AliExpress einschalten und nach dem Einkaufen wieder abschalten. Das wird man bei einigen Seiten auch auf lange Sicht nicht ganz vermeiden können.

**Comment by M-Reimer** [comment]
War noch ein Bug in der letzten Version. Bitte nochmal testen. Bis zum Formular komme ich. Mangels Account und Bedarf einen solchen anzulegen kann ich nicht weiter testen.

**Comment by stonecrusher** [comment]
Habe es gerade getestet und es funktioniert. Vielen Dank für die schnelle Rückmeldung und den Fix!
