### ISSUE TITLE
Whitelist feature request

### ISSUE THREAD

**Issue by flexchar** [M-Reimer/togglereferrer#9]
Hey, first of all amazing work, I love this addon!

But it would be even more awesome if I could have a list of whitelisted domains and enable referrer header on those requests.

**Comment by M-Reimer** [comment]
The idea is that you temporarily toggle on your referrer for such servers.

If there are big sites which force referrer to be on I can add them to the internal spoofing feature. If that's the case please open issues for the individual sites.
